--                                 Exploratory Data Analysis (EDA)

-- Questions
-- Total number of orders.
-- Total customers. 
-- Total products.
-- Total sellers. 
-- Total revenue. 
-- Average order value. 
-- Revenue distribution. 
-- Order status distribution. 
-- Monthly order volume. 
-- Customer distribution by state.

--  1.  Total number of orders.
SELECT COUNT(order_id) AS Total_No_orders
FROM orders;
--  Total Number of Orders placed are 99441.

-- 2. Total customers.
SELECT COUNT(customer_id) AS Total_Customers
FROM customers;
--  Total Customers are 99441 present

-- 3. Total products.
SELECT COUNT(product_id) AS Total_product
FROM products;
-- Total products are 32951

-- 4.  Total sellers.
SELECT COUNT(seller_id) AS total_seller
FROM sellers;
--  Total sellers are 3095

-- 5. Total revenue.
SELECT SUM(price) AS Total_revenue 
FROM order_items;
--  Total Revenue Generated is 13591643.70

-- 6. Average order value.
SELECT
SUM(price) / COUNT(DISTINCT order_id) AS avg_order_value
FROM order_items;
--  Average value of order is 137.7540763788944520

-- 7. Revenue distribution.

--  Revenue distrubution per product_category_name
SELECT p.product_category_name, ROUND(SUM(oi.price)) AS total_revenue
FROM products AS p JOIN order_items AS oi
ON p.product_id = oi.product_id
GROUP BY  p.product_category_name
ORDER BY SUM(price) DESC;
-- category_name "beleza_saude"	has created highest Revenue 1258681
--  and very low revenue is generated by "seguros_e_servicos" only 283

-- Revenue distrubution by customer_state
SELECT c.customer_state, ROUND(SUM(price)) AS total_revenue
FROM order_items AS oi JOIN
orders AS o ON oi.order_id = o.order_id
JOIN customers AS c ON c.customer_id = o.customer_id
GROUP BY c.customer_state
order by SUM(price) DESC;

--  8. Order status distribution.
SELECT order_status, COUNT(*) AS order_status_count
FROM orders 
GROUP BY order_status
ORDER BY COUNT(*) DESC;
--  Most of the products are delivered as compare canceled products are less

-- 9.  Monthly order volume.
SELECT
TO_CHAR(order_purchase_timestamp, 'YYYY-MM')  AS month,
COUNT(order_id) AS total_orders
FROM orders
GROUP BY month
ORDER BY month;


-- 10.  Customer distribution by state.
SELECT customer_state,
COUNT(customer_id) AS customer_count
FROM customers
GROUP BY customer_state
ORDER BY COUNT(customer_id) DESC;
-- from state "SP" their are more customers taht is 41746 present
-- state RR has low customers






